# This file was generated by GoReleaser. DO NOT EDIT.
cask "strive" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "b27ea1660cff9e8f11dbb3ffa4a45595d450904c4cd5e3c09b9e42a5930af668"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff30f1d2b8a2db0c9f9a1a2664b1d118d8c1de127f051c2208737c7370c5db6e"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "05a6da01cf179f45c4cea37060f9d3330361ed145cbaf4af99dda529ee1ff785"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c5af3a39575871fab46f87e2bf74dfe5393b78c4712910722a104b824ce3a771"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_linux_amd64.tar.gz"
    end
  end

  name "strive"
  desc "Strive planner from the command line"
  homepage "https://striveplanner.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "strive"
  bash_completion "completions/strive.bash"
  fish_completion "completions/strive.fish"
  zsh_completion "completions/strive.zsh"

  # No zap stanza required
end
