# This file was generated by GoReleaser. DO NOT EDIT.
cask "strive" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "b7c16fc80a6b2be84fb61df3f2e02baa24d5db744158f7a4aa976de23f71cccb"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c01669a4ae450316e0186de5af823e79dd7033ac94c57502bc233c9d502f06a3"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9649e6d30e1d47d982dd20c8e1226796a77c7e2de314a2b24b9262d04f2077e7"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "333c7ab3b58d4aadc78d1a74fc57c9d83915b5aa0d57f383e0dd6440afd22be1"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_linux_amd64.tar.gz"
    end
  end

  name "strive"
  desc "Strive planner from the command line"
  homepage "https://striveplanner.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "strive"
  bash_completion "completions/strive.bash"
  fish_completion "completions/strive.fish"
  zsh_completion "completions/strive.zsh"

  # No zap stanza required
end
