# This file was generated by GoReleaser. DO NOT EDIT.
cask "strive" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "ddcb517a8002ab6334b4adda44cda2f38dae5f3056fd083d054c2cdcad29b53d"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "be6ccf6565309000d92c4cbadda384fa3706f3cb57a880dae43a90a4ea2ea298"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4c30f1ea114fb9f52e2987973d6aa897b98da9bf6fccd9bcc68351a7b5ccc2d6"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5e75170cad37eb75f4949c3c805200a4d3947254e4bed7f7e6594a798b7a18c6"
      url "https://github.com/MikaelWeiss/strive-cli/releases/download/v#{version}/strive_#{version}_linux_amd64.tar.gz"
    end
  end

  name "strive"
  desc "Strive planner from the command line"
  homepage "https://striveplanner.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "strive"
  bash_completion "completions/strive.bash"
  fish_completion "completions/strive.fish"
  zsh_completion "completions/strive.zsh"

  # No zap stanza required
end
